/*****************************************
 *                                       *
 * This file is automatically generated. *
 * To create new hardfork, please modify *
 * the .hf files in hardfork.d instead   *
 * of modifying this file.               *
 *                                       *
 *****************************************/

#pragma once
// CHECK_REVIEW_PERIOD_TIME
#ifndef CHECK_REVIEW_PERIOD_TIME
#define CHECK_REVIEW_PERIOD_TIME (fc::time_point_sec( 1518162390 ))
#endif
// Increase the contract object 尝试添加合约对象
#ifndef INCREASE_CONTRACT
#define INCREASE_CONTRACT (fc::time_point_sec( 1523156702 ))
#endif
